services:
  postgres:
    image: postgres:15
    container_name: crud_postgres
    restart: always
    environment:
      POSTGRES_DB: aval_acao_crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crud_network
    command: >
        postgres-c listen_addresses='*'
        postgres-c max_connections=100
        postgres-c shared_buffers=256MB
  web:
    image: php:8.2-apache
    container_name: crud_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
    networks:
      - crud_network
    environment:
      - POSTGRES_HOST = db
      POSTGRES_DB = aval_acao_crud
      POSTGRES_USER = postgres
      POSTGRES_PASSWORD = postgres123
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y libpq-dev &&
        docker-php-ext.install pdo pdo_pgsql &&
        apache2-foreground
        "
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: crud_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - crud_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
  pgadmin_data:
networks:
  crud_network:
    driver: bridge
      
